from loguru import logger
from langchain_core.runnables import RunnableConfig
from baml_client.async_client import b as async_b
from app.services.context_engine import build_context, to_baml_messages

async def specialist_node(
    state: dict,
    config: RunnableConfig,
) -> dict:
    """Generic node to handle any specialist department.
    Appends blueprint or advice to the aggregated state."""
    collector = config.get("configurable", {}).get("collector")

    context, processed_msgs = await build_context(
        user_info=state.get("user_info"),
        include_db_state=False,
        messages=state.get("messages", []),
        previous_tool_results=state.get("previous_tool_results", [])
    )
    baml_msgs = to_baml_messages(processed_msgs)
    
    stages = state.get("stages", [])
    current_dept = state.get("current_dept")

    if not current_dept:
        if not stages:
            logger.warning("No stages found in state!")
            return {"error": "No stages found to execute"}
        current_stage = stages[0]
        deps = current_stage.get("departments", [])
        if not deps:
            return {"error": f"No departments found in stage {current_stage.get('order')}"}
        current_dept = deps[0]

    specialist_func_name = f"{current_dept.capitalize()}Specialist"
    specialist_func = getattr(async_b, specialist_func_name, None)

    if not specialist_func:
        logger.error(f"Failed to find BAML function {specialist_func_name} for department {current_dept}")
        return {"error": f"Unsupported department: {current_dept}"}
    
    logger.info(f"Running specialist: {current_dept}")
    res = await specialist_func(
        input={
            "query": state["query"],
            "context": context,
            "history": baml_msgs,
        },
        baml_options={"collector": collector} if collector else {},
    )
    logger.info(f"Specialist {current_dept} response: {res}")
    
    # Handle Advice object (non-action response)
    if hasattr(res, "content"):
        return {"advices": [res.content]}
    
    # Handle Blueprint object (action required)
    return {"blueprints": [res]}

async def context_synthesizer_node(state: dict) -> dict:
    """Fan-in node: Collects all blueprints and advices from parallel specialists."""
    if not state.get("blueprints") and state.get("advices"):
        combined_advice = "\n\n".join(state["advices"])
        return {"response": combined_advice, "blueprints": [], "advices": []}
    
    if state.get("blueprints"):
        from baml_client.types import Blueprint
        combined_objective = " AND ".join([bp.objective for bp in state["blueprints"]])
        combined_thoughts = "\n".join([bp.thought for bp in state["blueprints"] if bp.thought])
        
        master_blueprint = Blueprint(objective=combined_objective, thought=combined_thoughts)
        return {"blueprint": master_blueprint, "response": None, "blueprints": [], "advices": []}
    
    return {"error": "No blueprints or advices generated by specialists."}
