# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AgentStepResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AgentStep", llm_response=llm_response, mode="request")
        return typing.cast(types.AgentStepResponse, __result__)

    def AnalyticsSpecialist(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.Blueprint", "types.Advice"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyticsSpecialist", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.Blueprint", "types.Advice"], __result__)

    def EvaluateWorkflow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.QCResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateWorkflow", llm_response=llm_response, mode="request")
        return typing.cast(types.QCResult, __result__)

    def ExecuteTool(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StepExecution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExecuteTool", llm_response=llm_response, mode="request")
        return typing.cast(types.StepExecution, __result__)

    def Executor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StepExecution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Executor", llm_response=llm_response, mode="request")
        return typing.cast(types.StepExecution, __result__)

    def ManagementSpecialist(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.Blueprint", "types.Advice"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ManagementSpecialist", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.Blueprint", "types.Advice"], __result__)

    def MyFunction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MyFunction", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def Orchestrator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.OrchestratorResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Orchestrator", llm_response=llm_response, mode="request")
        return typing.cast(types.OrchestratorResult, __result__)

    def Planner(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Plan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Planner", llm_response=llm_response, mode="request")
        return typing.cast(types.Plan, __result__)

    def Responsor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Responsor", llm_response=llm_response, mode="request")
        return typing.cast(types.AgentResponse, __result__)

    def Validator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Validator", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidationResult, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AgentStepResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AgentStep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AgentStepResponse, __result__)

    def AnalyticsSpecialist(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.Blueprint", "stream_types.Advice"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyticsSpecialist", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.Blueprint", "stream_types.Advice"], __result__)

    def EvaluateWorkflow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.QCResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateWorkflow", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.QCResult, __result__)

    def ExecuteTool(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StepExecution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExecuteTool", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StepExecution, __result__)

    def Executor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StepExecution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Executor", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StepExecution, __result__)

    def ManagementSpecialist(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.Blueprint", "stream_types.Advice"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ManagementSpecialist", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.Blueprint", "stream_types.Advice"], __result__)

    def MyFunction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MyFunction", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def Orchestrator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.OrchestratorResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Orchestrator", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.OrchestratorResult, __result__)

    def Planner(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Plan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Planner", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Plan, __result__)

    def Responsor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AgentResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Responsor", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AgentResponse, __result__)

    def Validator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Validator", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidationResult, __result__)

    