# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def AgentStep(self, user_message: str,history: typing.List["types.Messages"],state: typing.Optional["types.AgentState"] = None,previous_results: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.AgentStepResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AgentStep(user_message=user_message,history=history,state=state,previous_results=previous_results,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AgentStep", args={
                "user_message": user_message,"history": history,"state": state,"previous_results": previous_results,
            })
            return typing.cast(types.AgentStepResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def AnalyticsSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.Blueprint", "types.Advice"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnalyticsSpecialist(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyticsSpecialist", args={
                "input": input,
            })
            return typing.cast(typing.Union["types.Blueprint", "types.Advice"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def EvaluateWorkflow(self, input: types.QCInput,
        baml_options: BamlCallOptions = {},
    ) -> types.QCResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.EvaluateWorkflow(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="EvaluateWorkflow", args={
                "input": input,
            })
            return typing.cast(types.QCResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExecuteTool(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StepExecution:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExecuteTool(query=query,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExecuteTool", args={
                "query": query,
            })
            return typing.cast(types.StepExecution, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def Executor(self, input: types.ExecutorInput,
        baml_options: BamlCallOptions = {},
    ) -> types.StepExecution:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.Executor(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="Executor", args={
                "input": input,
            })
            return typing.cast(types.StepExecution, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ManagementSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.Blueprint", "types.Advice"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ManagementSpecialist(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ManagementSpecialist", args={
                "input": input,
            })
            return typing.cast(typing.Union["types.Blueprint", "types.Advice"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def MyFunction(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.MyFunction(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="MyFunction", args={
                "input": input,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def Orchestrator(self, query: str,context: str,messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> types.OrchestratorResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.Orchestrator(query=query,context=context,messages=messages,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="Orchestrator", args={
                "query": query,"context": context,"messages": messages,
            })
            return typing.cast(types.OrchestratorResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def Planner(self, input: types.PlannerInput,
        baml_options: BamlCallOptions = {},
    ) -> types.Plan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.Planner(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="Planner", args={
                "input": input,
            })
            return typing.cast(types.Plan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def Responsor(self, query: str,context: str,plan: typing.Optional[str],tool_history: typing.Optional[str],validator_reasoning: typing.Optional[str],messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.Responsor(query=query,context=context,plan=plan,tool_history=tool_history,validator_reasoning=validator_reasoning,messages=messages,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="Responsor", args={
                "query": query,"context": context,"plan": plan,"tool_history": tool_history,"validator_reasoning": validator_reasoning,"messages": messages,
            })
            return typing.cast(types.AgentResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def Validator(self, input: types.ValidatorInput,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.Validator(input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="Validator", args={
                "input": input,
            })
            return typing.cast(types.ValidationResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentStep(self, user_message: str,history: typing.List["types.Messages"],state: typing.Optional["types.AgentState"] = None,previous_results: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AgentStepResponse, types.AgentStepResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AgentStep", args={
            "user_message": user_message,"history": history,"state": state,"previous_results": previous_results,
        })
        return baml_py.BamlSyncStream[stream_types.AgentStepResponse, types.AgentStepResponse](
          __result__,
          lambda x: typing.cast(stream_types.AgentStepResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AgentStepResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AnalyticsSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.Blueprint", "stream_types.Advice"], typing.Union["types.Blueprint", "types.Advice"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyticsSpecialist", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.Blueprint", "stream_types.Advice"], typing.Union["types.Blueprint", "types.Advice"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.Blueprint", "stream_types.Advice"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.Blueprint", "types.Advice"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def EvaluateWorkflow(self, input: types.QCInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QCResult, types.QCResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="EvaluateWorkflow", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[stream_types.QCResult, types.QCResult](
          __result__,
          lambda x: typing.cast(stream_types.QCResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QCResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExecuteTool(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.StepExecution, types.StepExecution]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExecuteTool", args={
            "query": query,
        })
        return baml_py.BamlSyncStream[stream_types.StepExecution, types.StepExecution](
          __result__,
          lambda x: typing.cast(stream_types.StepExecution, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StepExecution, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def Executor(self, input: types.ExecutorInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.StepExecution, types.StepExecution]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="Executor", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[stream_types.StepExecution, types.StepExecution](
          __result__,
          lambda x: typing.cast(stream_types.StepExecution, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StepExecution, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ManagementSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.Blueprint", "stream_types.Advice"], typing.Union["types.Blueprint", "types.Advice"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ManagementSpecialist", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.Blueprint", "stream_types.Advice"], typing.Union["types.Blueprint", "types.Advice"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.Blueprint", "stream_types.Advice"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.Blueprint", "types.Advice"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def MyFunction(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="MyFunction", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def Orchestrator(self, query: str,context: str,messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OrchestratorResult, types.OrchestratorResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="Orchestrator", args={
            "query": query,"context": context,"messages": messages,
        })
        return baml_py.BamlSyncStream[stream_types.OrchestratorResult, types.OrchestratorResult](
          __result__,
          lambda x: typing.cast(stream_types.OrchestratorResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OrchestratorResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def Planner(self, input: types.PlannerInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Plan, types.Plan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="Planner", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[stream_types.Plan, types.Plan](
          __result__,
          lambda x: typing.cast(stream_types.Plan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Plan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def Responsor(self, query: str,context: str,plan: typing.Optional[str],tool_history: typing.Optional[str],validator_reasoning: typing.Optional[str],messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AgentResponse, types.AgentResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="Responsor", args={
            "query": query,"context": context,"plan": plan,"tool_history": tool_history,"validator_reasoning": validator_reasoning,"messages": messages,
        })
        return baml_py.BamlSyncStream[stream_types.AgentResponse, types.AgentResponse](
          __result__,
          lambda x: typing.cast(stream_types.AgentResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AgentResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def Validator(self, input: types.ValidatorInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="Validator", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult](
          __result__,
          lambda x: typing.cast(stream_types.ValidationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentStep(self, user_message: str,history: typing.List["types.Messages"],state: typing.Optional["types.AgentState"] = None,previous_results: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AgentStep", args={
            "user_message": user_message,"history": history,"state": state,"previous_results": previous_results,
        }, mode="request")
        return __result__
    def AnalyticsSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyticsSpecialist", args={
            "input": input,
        }, mode="request")
        return __result__
    def EvaluateWorkflow(self, input: types.QCInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluateWorkflow", args={
            "input": input,
        }, mode="request")
        return __result__
    def ExecuteTool(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExecuteTool", args={
            "query": query,
        }, mode="request")
        return __result__
    def Executor(self, input: types.ExecutorInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Executor", args={
            "input": input,
        }, mode="request")
        return __result__
    def ManagementSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ManagementSpecialist", args={
            "input": input,
        }, mode="request")
        return __result__
    def MyFunction(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MyFunction", args={
            "input": input,
        }, mode="request")
        return __result__
    def Orchestrator(self, query: str,context: str,messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Orchestrator", args={
            "query": query,"context": context,"messages": messages,
        }, mode="request")
        return __result__
    def Planner(self, input: types.PlannerInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Planner", args={
            "input": input,
        }, mode="request")
        return __result__
    def Responsor(self, query: str,context: str,plan: typing.Optional[str],tool_history: typing.Optional[str],validator_reasoning: typing.Optional[str],messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Responsor", args={
            "query": query,"context": context,"plan": plan,"tool_history": tool_history,"validator_reasoning": validator_reasoning,"messages": messages,
        }, mode="request")
        return __result__
    def Validator(self, input: types.ValidatorInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Validator", args={
            "input": input,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentStep(self, user_message: str,history: typing.List["types.Messages"],state: typing.Optional["types.AgentState"] = None,previous_results: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AgentStep", args={
            "user_message": user_message,"history": history,"state": state,"previous_results": previous_results,
        }, mode="stream")
        return __result__
    def AnalyticsSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyticsSpecialist", args={
            "input": input,
        }, mode="stream")
        return __result__
    def EvaluateWorkflow(self, input: types.QCInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluateWorkflow", args={
            "input": input,
        }, mode="stream")
        return __result__
    def ExecuteTool(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExecuteTool", args={
            "query": query,
        }, mode="stream")
        return __result__
    def Executor(self, input: types.ExecutorInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Executor", args={
            "input": input,
        }, mode="stream")
        return __result__
    def ManagementSpecialist(self, input: types.SpecialistInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ManagementSpecialist", args={
            "input": input,
        }, mode="stream")
        return __result__
    def MyFunction(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MyFunction", args={
            "input": input,
        }, mode="stream")
        return __result__
    def Orchestrator(self, query: str,context: str,messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Orchestrator", args={
            "query": query,"context": context,"messages": messages,
        }, mode="stream")
        return __result__
    def Planner(self, input: types.PlannerInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Planner", args={
            "input": input,
        }, mode="stream")
        return __result__
    def Responsor(self, query: str,context: str,plan: typing.Optional[str],tool_history: typing.Optional[str],validator_reasoning: typing.Optional[str],messages: typing.List["types.Messages"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Responsor", args={
            "query": query,"context": context,"plan": plan,"tool_history": tool_history,"validator_reasoning": validator_reasoning,"messages": messages,
        }, mode="stream")
        return __result__
    def Validator(self, input: types.ValidatorInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Validator", args={
            "input": input,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))