# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Advice": types.Advice,
    "stream_types.Advice": stream_types.Advice,

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.AgentResponseBlock": types.AgentResponseBlock,
    "stream_types.AgentResponseBlock": stream_types.AgentResponseBlock,

    "types.AgentState": types.AgentState,
    "stream_types.AgentState": stream_types.AgentState,

    "types.AgentStepResponse": types.AgentStepResponse,
    "stream_types.AgentStepResponse": stream_types.AgentStepResponse,

    "types.AnomalyReport": types.AnomalyReport,
    "stream_types.AnomalyReport": stream_types.AnomalyReport,

    "types.Blueprint": types.Blueprint,
    "stream_types.Blueprint": stream_types.Blueprint,

    "types.BreakdownData": types.BreakdownData,
    "stream_types.BreakdownData": stream_types.BreakdownData,

    "types.CallTool": types.CallTool,
    "stream_types.CallTool": stream_types.CallTool,

    "types.ChartConfig": types.ChartConfig,
    "stream_types.ChartConfig": stream_types.ChartConfig,

    "types.ChartData": types.ChartData,
    "stream_types.ChartData": stream_types.ChartData,

    "types.ChartDataPoint": types.ChartDataPoint,
    "stream_types.ChartDataPoint": stream_types.ChartDataPoint,

    "types.ChartSeries": types.ChartSeries,
    "stream_types.ChartSeries": stream_types.ChartSeries,

    "types.Context": types.Context,
    "stream_types.Context": stream_types.Context,

    "types.CustomProperty": types.CustomProperty,
    "stream_types.CustomProperty": stream_types.CustomProperty,

    "types.DynamicTool": types.DynamicTool,
    "stream_types.DynamicTool": stream_types.DynamicTool,

    "types.EventTool": types.EventTool,
    "stream_types.EventTool": stream_types.EventTool,

    "types.ExecutorInput": types.ExecutorInput,
    "stream_types.ExecutorInput": stream_types.ExecutorInput,

    "types.FocusData": types.FocusData,
    "stream_types.FocusData": stream_types.FocusData,

    "types.FocusTask": types.FocusTask,
    "stream_types.FocusTask": stream_types.FocusTask,

    "types.GoalProgressItem": types.GoalProgressItem,
    "stream_types.GoalProgressItem": stream_types.GoalProgressItem,

    "types.GoalTool": types.GoalTool,
    "stream_types.GoalTool": stream_types.GoalTool,

    "types.InsightData": types.InsightData,
    "stream_types.InsightData": stream_types.InsightData,

    "types.Messages": types.Messages,
    "stream_types.Messages": stream_types.Messages,

    "types.MilestoneItem": types.MilestoneItem,
    "stream_types.MilestoneItem": stream_types.MilestoneItem,

    "types.OrchestratorResult": types.OrchestratorResult,
    "stream_types.OrchestratorResult": stream_types.OrchestratorResult,

    "types.OrchestratorStage": types.OrchestratorStage,
    "stream_types.OrchestratorStage": stream_types.OrchestratorStage,

    "types.Plan": types.Plan,
    "stream_types.Plan": stream_types.Plan,

    "types.PlannerInput": types.PlannerInput,
    "stream_types.PlannerInput": stream_types.PlannerInput,

    "types.QCInput": types.QCInput,
    "stream_types.QCInput": stream_types.QCInput,

    "types.QCResult": types.QCResult,
    "stream_types.QCResult": stream_types.QCResult,

    "types.QCTestCase": types.QCTestCase,
    "stream_types.QCTestCase": stream_types.QCTestCase,

    "types.QCWorkflowEvent": types.QCWorkflowEvent,
    "stream_types.QCWorkflowEvent": stream_types.QCWorkflowEvent,

    "types.ReflectionData": types.ReflectionData,
    "stream_types.ReflectionData": stream_types.ReflectionData,

    "types.ReflectionQuestion": types.ReflectionQuestion,
    "stream_types.ReflectionQuestion": stream_types.ReflectionQuestion,

    "types.RescheduleData": types.RescheduleData,
    "stream_types.RescheduleData": stream_types.RescheduleData,

    "types.RescheduleItem": types.RescheduleItem,
    "stream_types.RescheduleItem": stream_types.RescheduleItem,

    "types.SearchTool": types.SearchTool,
    "stream_types.SearchTool": stream_types.SearchTool,

    "types.SpecialistInput": types.SpecialistInput,
    "stream_types.SpecialistInput": stream_types.SpecialistInput,

    "types.Step": types.Step,
    "stream_types.Step": stream_types.Step,

    "types.StepExecution": types.StepExecution,
    "stream_types.StepExecution": stream_types.StepExecution,

    "types.TaskTool": types.TaskTool,
    "stream_types.TaskTool": stream_types.TaskTool,

    "types.ToolResult": types.ToolResult,
    "stream_types.ToolResult": stream_types.ToolResult,

    "types.ValidationResult": types.ValidationResult,
    "stream_types.ValidationResult": stream_types.ValidationResult,

    "types.ValidatorInput": types.ValidatorInput,
    "stream_types.ValidatorInput": stream_types.ValidatorInput,


    "types.BlueprintStatus": types.BlueprintStatus,

    "types.ChartVisualizationType": types.ChartVisualizationType,

    "types.ComponentType": types.ComponentType,

    "types.Department": types.Department,

    "types.ValidationDecision": types.ValidationDecision,

}