# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (5)
# #########################################################################

class BlueprintStatus(str, Enum):
    READY_TO_PLAN = "READY_TO_PLAN"
    ALREADY_DONE = "ALREADY_DONE"

class ChartVisualizationType(str, Enum):
    BAR = "BAR"
    LINE = "LINE"
    PIE = "PIE"
    AREA = "AREA"
    RADIAL = "RADIAL"
    SPARKLINE = "SPARKLINE"
    STAT_CARD = "STAT_CARD"
    PROGRESS = "PROGRESS"

class ComponentType(str, Enum):
    TEXT = "TEXT"
    CHART = "CHART"
    BREAKDOWN = "BREAKDOWN"
    INSIGHT = "INSIGHT"
    FOCUS = "FOCUS"
    RESCHEDULE = "RESCHEDULE"
    REFLECTION = "REFLECTION"

class Department(str, Enum):
    MANAGEMENT = "MANAGEMENT"
    ANALYTICS = "ANALYTICS"
    CHAT = "CHAT"

class ValidationDecision(str, Enum):
    PASS = "PASS"
    RETRY = "RETRY"
    REPLAN = "REPLAN"
    AMBIGUOUS = "AMBIGUOUS"
    FAIL = "FAIL"

# #########################################################################
# Generated classes (45)
# #########################################################################

class Advice(BaseModel):
    content: str = Field(description='A conversational response giving advice, answering a question, or requesting clarification.')

class AgentResponse(BaseModel):
    blocks: typing.List["AgentResponseBlock"] = Field(description='An ordered list of UI blocks to render sequentially from top to bottom.')

class AgentResponseBlock(BaseModel):
    component_type: ComponentType = Field(description='Choose the appropriate component type for this block.')
    text: typing.Optional[str] = Field(default=None, description='Conversational text. Required if component_type is TEXT.')
    chart_data: typing.Optional["ChartData"] = Field(default=None, description='Dynamic chart data. Required if component_type is CHART.')
    breakdown_data: typing.Optional["BreakdownData"] = Field(default=None, description='Goal breakdown data. Required if component_type is BREAKDOWN.')
    insight_data: typing.Optional["InsightData"] = Field(default=None, description='Dashboard insight data. Required if component_type is INSIGHT.')
    focus_data: typing.Optional["FocusData"] = Field(default=None, description='Today\'s focus tasks. Required if component_type is FOCUS.')
    reschedule_data: typing.Optional["RescheduleData"] = Field(default=None, description='Reschedule suggestions. Required if component_type is RESCHEDULE.')
    reflection_data: typing.Optional["ReflectionData"] = Field(default=None, description='Weekly reflection data. Required if component_type is REFLECTION.')

class AgentState(BaseModel):
    current_objective: str = Field(description='The main goal the user is trying to achieve')
    completed_steps: typing.List[str] = Field(description='List of actions already taken')
    gathered_info: str = Field(description='Context collected from tool results so far')

class AgentStepResponse(BaseModel):
    reasoning: typing.Optional[str] = Field(default=None, description='Step-by-step thinking about what the user wants and what to do next.')
    thought_process: typing.Optional[str] = Field(default=None, description='Detailed mental model: 1. Identify intent, 2. Check missing info, 3. Choose tool.')
    needs_more_tools: bool = Field(description='True if we need to call a tool before answering. False if we have enough info.')
    tool_choice: typing.Optional[typing.Union["TaskTool", "EventTool", "GoalTool", "SearchTool"]] = Field(default=None, description='The tool to use next, or null if giving final answer.')
    final_answer: typing.Optional[str] = Field(default=None, description='The final response to the user if needs_more_tools is false.')

class AnomalyReport(BaseModel):
    step_number: typing.Optional[int] = Field(default=None, description='The step number where the anomaly occurred, if applicable.')
    severity: str = Field(description='e.g., LOW, MEDIUM, HIGH, CRITICAL')
    issue_description: str = Field(description='Detailed explanation of what went wrong or seemed illogical.')
    suggested_fix: str = Field(description='How the agent should have behaved instead.')

class Blueprint(BaseModel):
    objective: str = Field(description='The overarching goal the user wants to achieve.')
    thought: typing.Optional[str] = Field(default=None, description='Expert reasoning or clarifications that help the Planner understand why certain constraints exist.')

class BreakdownData(BaseModel):
    goal_title: str = Field(description='The original goal being broken down')
    milestones: typing.List["MilestoneItem"] = Field(description='Ordered list of milestones with timeline')

class CallTool(BaseModel):
    model_config = ConfigDict(extra='allow')

class ChartConfig(BaseModel):
    type: ChartVisualizationType = Field(description='Preferred visualization type.')
    x_axis_label: typing.Optional[str] = Field(default=None, description='Label for X-axis (if applicable)')
    y_axis_label: typing.Optional[str] = Field(default=None, description='Label for Y-axis (if applicable)')
    show_legend: typing.Optional[bool] = Field(default=None, description='Whether to show the legend.')
    options: typing.Optional[typing.Dict[str, typing.Union[str, int, float]]] = Field(default=None, description='Type-specific options. Each chart type accepts different keys — see ChartVisualizationType descriptions for available options.')

class ChartData(BaseModel):
    title: typing.Optional[str] = Field(default=None, description='Optional title for the chart.')
    config: "ChartConfig" = Field(description='Visualization configuration.')
    series: typing.List["ChartSeries"] = Field(description='List of data series to plot. Supports multi-line or grouped charts.')

class ChartDataPoint(BaseModel):
    x: str = Field(description='The X-axis value (e.g., date \'2026-03-10\', or category \'Project A\')')
    y: float = Field(description='The Y-axis value (e.g., 15.5, 10)')

class ChartSeries(BaseModel):
    label: typing.Optional[str] = Field(default=None, description='Name of this series for the Legend (e.g., \'Revenue\', \'Time Spent\')')
    data: typing.List["ChartDataPoint"] = Field(description='The data points for this specific series')

class Context(BaseModel):
    user_info: typing.Optional[str] = None
    current_time: str

class CustomProperty(BaseModel):
    name: str
    value: str

class DynamicTool(BaseModel):
    model_config = ConfigDict(extra='allow')

class EventTool(BaseModel):
    id: typing.Optional[str] = None
    title: str
    start_time: str
    end_time: typing.Optional[str] = None

class ExecutorInput(BaseModel):
    context: str
    step_description: str
    allowed_tools: typing.List[str]

class FocusData(BaseModel):
    date: str = Field(description='Today\'s date in ISO format')
    tasks: typing.List["FocusTask"] = Field(description='Top 3 priority tasks for today')

class FocusTask(BaseModel):
    task_id: str = Field(description='UUID of the task')
    title: str = Field(description='Task title')
    goal_tag: typing.Optional[str] = Field(default=None, description='Name of the associated goal, if any')
    estimated_minutes: typing.Optional[int] = Field(default=None, description='Estimated time in minutes')
    is_completed: bool = Field(description='Whether the task is already completed')

class GoalProgressItem(BaseModel):
    goal_title: str = Field(description='Name of the goal')
    progress_pct: float = Field(description='Progress percentage from 0.0 to 1.0')
    status: str = Field(description='One of: on_track, behind, at_risk')

class GoalTool(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='The ID of the goal if known')
    title: str
    description: typing.Optional[str] = None
    status: typing.Optional[str] = Field(default=None, description='active, completed, etc.')
    start_date: typing.Optional[str] = None
    end_date: typing.Optional[str] = None

class InsightData(BaseModel):
    tasks_done: int = Field(description='Number of tasks completed')
    tasks_overdue: int = Field(description='Number of overdue tasks')
    tasks_on_track: int = Field(description='Number of tasks on track')
    goal_progress: typing.List["GoalProgressItem"] = Field(description='Progress per goal')
    warnings: typing.List[str] = Field(description='Warning messages for items behind schedule')

class Messages(BaseModel):
    role: typing.Union[typing_extensions.Literal['system'], typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    content: str

class MilestoneItem(BaseModel):
    title: str = Field(description='Title of the milestone')
    deadline: typing.Optional[str] = Field(default=None, description='Suggested deadline in ISO date format (e.g. 2026-04-15)')
    description: typing.Optional[str] = Field(default=None, description='Brief description of what this milestone involves')
    subtasks: typing.Optional[typing.List["MilestoneItem"]] = Field(default=None, description='Optional sub-steps to achieve this specific milestone')

class OrchestratorResult(BaseModel):
    stages: typing.List["OrchestratorStage"] = Field(description='The ordered sequence of stages to fulfill the user intent. Stages are executed sequentially, but departments within a stage can be parallel.')
    chat_response: typing.Optional[str] = Field(default=None, description='The conversational response if \'CHAT\' is the ONLY department in the stages. Leave empty otherwise.')

class OrchestratorStage(BaseModel):
    order: int
    departments: typing.List[Department] = Field(description='The departments responsible for this specific stage. Multiple departments here mean they can be executed in parallel.')

class Plan(BaseModel):
    reasoning: typing.Optional[str] = Field(default=None, description='High-level thought process about the user\'s overall goal.')
    steps: typing.Optional[typing.List["Step"]] = Field(default=None, description='A logic sequence of steps to fulfill the request.')

class PlannerInput(BaseModel):
    context: str
    specialist_name: str
    blueprint: "Blueprint"
    tool_results: typing.Optional[typing.List["ToolResult"]] = None
    allowed_tools: typing.List[str]

class QCInput(BaseModel):
    test_case: "QCTestCase"
    workflow_events: typing.List["QCWorkflowEvent"]
    final_agent_response: str

class QCResult(BaseModel):
    is_valid: bool = Field(description='True if the workflow perfectly matched the expected outcome with no critical logic errors, false otherwise.')
    anomalies: typing.List["AnomalyReport"] = Field(description='List of questionable actions, hallucinations, or deviations from the expected logic.')
    overall_evaluation: str = Field(description='A brief summary of the workflow execution quality.')

class QCTestCase(BaseModel):
    test_id: typing.Optional[str] = Field(default=None, description='Optional identifier for the test case.')
    intent: str = Field(description='The initial user request or intent of the test.')
    expected_outcome: str = Field(description='What should have happened or been the final response.')

class QCWorkflowEvent(BaseModel):
    step_number: int
    agent_name: str = Field(description='The name of the agent or component taking the action.')
    action: str = Field(description='The tool or action executed.')
    action_input: str = Field(description='The input parameters provided to the action.')
    action_output: str = Field(description='The result returned by the action.')

class ReflectionData(BaseModel):
    week_summary: typing.Optional[str] = Field(default=None, description='Brief summary of the past week\'s accomplishments')
    questions: typing.List["ReflectionQuestion"] = Field(description='3 guided reflection questions')
    cta_label: str = Field(description='Call-to-action button label (e.g. \'Start Journal Entry\')')
    cta_route: str = Field(description='Navigation route for the CTA (e.g. \'/journal\')')

class ReflectionQuestion(BaseModel):
    prompt: str = Field(description='The reflection question')
    placeholder: typing.Optional[str] = Field(default=None, description='Placeholder hint for the answer')

class RescheduleData(BaseModel):
    overdue_tasks: typing.List["RescheduleItem"] = Field(description='List of overdue tasks with suggested reschedule dates')

class RescheduleItem(BaseModel):
    task_id: str = Field(description='UUID of the overdue task')
    title: str = Field(description='Task title')
    original_due: str = Field(description='Original due date in ISO format')
    suggested_due: str = Field(description='AI-suggested new due date in ISO format')

class SearchTool(BaseModel):
    query: str = Field(description='Search query for goals, tasks, or events')

class SpecialistInput(BaseModel):
    query: str
    context: str
    history: typing.List["Messages"]

class Step(BaseModel):
    step: int
    description: str

class StepExecution(BaseModel):
    thought: typing.Optional[str] = Field(default=None, description='Expert reasoning for selecting this tool and how to populate its parameters.')
    tool_call: typing.Optional["DynamicTool"] = Field(default=None, description='The specific tool call to perform. MUST be provided if the step requires action.')

class TaskTool(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='The ID of the task if known')
    title: str
    due_date: typing.Optional[str] = None
    priority: typing.Optional[str] = None
    is_completed: typing.Optional[bool] = Field(default=None, description='Whether the task is finished')

class ToolResult(BaseModel):
    tool_name: str
    tool_input: typing.List[typing.Dict[str, str]]
    tool_output: str

class ValidationResult(BaseModel):
    reasoning: typing.Optional[str] = Field(default=None, description='MANDATORY for RETRY, REPLAN, FAIL, AMBIGUOUS. Set to null for PASS.')
    decision: ValidationDecision

class ValidatorInput(BaseModel):
    context: str
    plan: "Plan"
    current_step: int
    tool_results: typing.Optional[typing.List["ToolResult"]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
